spring.application.name=logistic-management

# YENİ BULUT VERİTABANI BAĞLANTISI (Neon)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate Ayarları
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Liquibase Ayarları
spring.liquibase.change-log=classpath:db/changelog/db-changelog-master.xml
spring.liquibase.enabled=true