spring.application.name=logistic-management

# Veritaban? Ba?lant? Bilgileri
spring.datasource.url=jdbc:postgresql://localhost:5432/logistic_db
spring.datasource.username=postgres
spring.datasource.password=grup12bravo

# JPA / Hibernate Ayarlar?
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Liquibase Ayarlar?
spring.liquibase.change-log=classpath:db/changelog/db-changelog-master.xml
spring.liquibase.enabled=true